# Generated by Django 3.1.4 on 2020-12-05 09:24

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ad')),
                ('lastname', models.CharField(max_length=100, verbose_name='soyad')),
                ('telephone', models.CharField(max_length=100, verbose_name='telefon')),
                ('email', models.EmailField(max_length=100, verbose_name='eposta')),
            ],
            options={
                'verbose_name_plural': 'TaSaRıMCı',
            },
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=100, null=True, verbose_name='en ust sırada yazılacak')),
                ('title2', models.CharField(blank=True, max_length=100, null=True, verbose_name='ortada yazılacak')),
                ('title3', models.CharField(blank=True, max_length=100, null=True, verbose_name='en alt')),
                ('link', models.URLField(blank=True, null=True, verbose_name='website')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim seçiniz')),
            ],
            options={
                'verbose_name_plural': 'sliderler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ad')),
                ('price', models.IntegerField(max_length=100, verbose_name='fiyat')),
                ('currency', models.CharField(choices=[('tl', 'TL'), ('usd', 'USD'), ('euro', 'EURO')], default='tl', max_length=5, verbose_name='kur')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim seçiniz')),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kadin', 'kadin'), ('erkek', 'erkek'), ('elektronik', 'elektronik'), ('sport', 'sport'), ('aksesuar', 'aksesuar'), ('makyaj', 'makyaj')], max_length=44, null=True, verbose_name='kategoriler')),
                ('shoesSize', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44')], max_length=26, null=True, verbose_name='ayakkabı numarası')),
                ('size', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('xs', 'xs'), ('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('xxxl', 'xxxl')], max_length=20, null=True, verbose_name='size')),
                ('color', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('red', 'red'), ('pink', 'pink'), ('orange', 'orange'), ('yellow', 'yellow'), ('purple', 'purple'), ('green', 'green'), ('blue', 'blue'), ('brown', 'brown'), ('black', 'black')], max_length=52, null=True, verbose_name='renk')),
                ('inDate', models.DateField(auto_now_add=True, null=True, verbose_name='giriş tarihi')),
                ('status', models.BooleanField(default=True, verbose_name='gösterilsin mi?')),
                ('designedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.designer', verbose_name='tasarımcı')),
            ],
            options={
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
